/**
 * Word's Shapes gallery, category by category (Insert ▸ Shapes). Every name is
 * an ST_ShapeType preset the geometry table can evaluate, so a picker can draw
 * each icon from the shape's own path. Lines/connectors and the text box are
 * not listed — the editor's line tool and text-box tool cover those.
 */

export interface ShapeGalleryCategory {
  category: string;
  items: { preset: string; label: string }[];
}

const item = (preset: string, label: string) => ({ preset, label });

export const SHAPE_GALLERY: ShapeGalleryCategory[] = [
  {
    category: "Rectangles",
    items: [
      item("rect", "Rectangle"),
      item("roundRect", "Rounded Rectangle"),
      item("snip1Rect", "Snip Single Corner Rectangle"),
      item("snip2SameRect", "Snip Same Side Corner Rectangle"),
      item("snip2DiagRect", "Snip Diagonal Corner Rectangle"),
      item("snipRoundRect", "Snip and Round Single Corner Rectangle"),
      item("round1Rect", "Round Single Corner Rectangle"),
      item("round2SameRect", "Round Same Side Corner Rectangle"),
      item("round2DiagRect", "Round Diagonal Corner Rectangle"),
    ],
  },
  {
    category: "Basic Shapes",
    items: [
      item("ellipse", "Oval"),
      item("triangle", "Isosceles Triangle"),
      item("rtTriangle", "Right Triangle"),
      item("parallelogram", "Parallelogram"),
      item("trapezoid", "Trapezoid"),
      item("diamond", "Diamond"),
      item("pentagon", "Regular Pentagon"),
      item("hexagon", "Hexagon"),
      item("heptagon", "Heptagon"),
      item("octagon", "Octagon"),
      item("decagon", "Decagon"),
      item("dodecagon", "Dodecagon"),
      item("pie", "Pie"),
      item("chord", "Chord"),
      item("teardrop", "Teardrop"),
      item("frame", "Frame"),
      item("halfFrame", "Half Frame"),
      item("corner", "L-Shape"),
      item("diagStripe", "Diagonal Stripe"),
      item("plus", "Cross"),
      item("plaque", "Plaque"),
      item("can", "Cylinder"),
      item("cube", "Cube"),
      item("bevel", "Bevel"),
      item("donut", "Donut"),
      item("noSmoking", "No Symbol"),
      item("blockArc", "Block Arc"),
      item("foldedCorner", "Folded Corner"),
      item("smileyFace", "Smiley Face"),
      item("heart", "Heart"),
      item("lightningBolt", "Lightning Bolt"),
      item("sun", "Sun"),
      item("moon", "Moon"),
      item("cloud", "Cloud"),
      item("arc", "Arc"),
      item("bracketPair", "Double Bracket"),
      item("bracePair", "Double Brace"),
      item("leftBracket", "Left Bracket"),
      item("rightBracket", "Right Bracket"),
      item("leftBrace", "Left Brace"),
      item("rightBrace", "Right Brace"),
    ],
  },
  {
    category: "Block Arrows",
    items: [
      item("rightArrow", "Right Arrow"),
      item("leftArrow", "Left Arrow"),
      item("upArrow", "Up Arrow"),
      item("downArrow", "Down Arrow"),
      item("leftRightArrow", "Left-Right Arrow"),
      item("upDownArrow", "Up-Down Arrow"),
      item("quadArrow", "Quad Arrow"),
      item("leftRightUpArrow", "Left-Right-Up Arrow"),
      item("bentArrow", "Bent Arrow"),
      item("uturnArrow", "U-Turn Arrow"),
      item("leftUpArrow", "Left-Up Arrow"),
      item("bentUpArrow", "Bent-Up Arrow"),
      item("curvedRightArrow", "Curved Right Arrow"),
      item("curvedLeftArrow", "Curved Left Arrow"),
      item("curvedUpArrow", "Curved Up Arrow"),
      item("curvedDownArrow", "Curved Down Arrow"),
      item("stripedRightArrow", "Striped Right Arrow"),
      item("notchedRightArrow", "Notched Right Arrow"),
      item("homePlate", "Pentagon Arrow"),
      item("chevron", "Chevron"),
      item("rightArrowCallout", "Right Arrow Callout"),
      item("downArrowCallout", "Down Arrow Callout"),
      item("leftArrowCallout", "Left Arrow Callout"),
      item("upArrowCallout", "Up Arrow Callout"),
      item("leftRightArrowCallout", "Left-Right Arrow Callout"),
      item("quadArrowCallout", "Quad Arrow Callout"),
      item("circularArrow", "Circular Arrow"),
    ],
  },
  {
    category: "Equation Shapes",
    items: [
      item("mathPlus", "Plus Sign"),
      item("mathMinus", "Minus Sign"),
      item("mathMultiply", "Multiplication Sign"),
      item("mathDivide", "Division Sign"),
      item("mathEqual", "Equal Sign"),
      item("mathNotEqual", "Not Equal Sign"),
    ],
  },
  {
    category: "Flowchart",
    items: [
      item("flowChartProcess", "Process"),
      item("flowChartAlternateProcess", "Alternate Process"),
      item("flowChartDecision", "Decision"),
      item("flowChartInputOutput", "Data"),
      item("flowChartPredefinedProcess", "Predefined Process"),
      item("flowChartInternalStorage", "Internal Storage"),
      item("flowChartDocument", "Document"),
      item("flowChartMultidocument", "Multidocument"),
      item("flowChartTerminator", "Terminator"),
      item("flowChartPreparation", "Preparation"),
      item("flowChartManualInput", "Manual Input"),
      item("flowChartManualOperation", "Manual Operation"),
      item("flowChartConnector", "Connector"),
      item("flowChartOffpageConnector", "Off-page Connector"),
      item("flowChartPunchedCard", "Card"),
      item("flowChartPunchedTape", "Punched Tape"),
      item("flowChartSummingJunction", "Summing Junction"),
      item("flowChartOr", "Or"),
      item("flowChartCollate", "Collate"),
      item("flowChartSort", "Sort"),
      item("flowChartExtract", "Extract"),
      item("flowChartMerge", "Merge"),
      item("flowChartOnlineStorage", "Stored Data"),
      item("flowChartDelay", "Delay"),
      item("flowChartMagneticTape", "Sequential Access Storage"),
      item("flowChartMagneticDisk", "Magnetic Disk"),
      item("flowChartMagneticDrum", "Direct Access Storage"),
      item("flowChartDisplay", "Display"),
    ],
  },
  {
    category: "Stars and Banners",
    items: [
      item("irregularSeal1", "Explosion 1"),
      item("irregularSeal2", "Explosion 2"),
      item("star4", "4-Point Star"),
      item("star5", "5-Point Star"),
      item("star6", "6-Point Star"),
      item("star7", "7-Point Star"),
      item("star8", "8-Point Star"),
      item("star10", "10-Point Star"),
      item("star12", "12-Point Star"),
      item("star16", "16-Point Star"),
      item("star24", "24-Point Star"),
      item("star32", "32-Point Star"),
      item("ribbon2", "Up Ribbon"),
      item("ribbon", "Down Ribbon"),
      item("ellipseRibbon2", "Curved Up Ribbon"),
      item("ellipseRibbon", "Curved Down Ribbon"),
      item("verticalScroll", "Vertical Scroll"),
      item("horizontalScroll", "Horizontal Scroll"),
      item("wave", "Wave"),
      item("doubleWave", "Double Wave"),
    ],
  },
  {
    category: "Callouts",
    items: [
      item("wedgeRectCallout", "Speech Bubble: Rectangle"),
      item("wedgeRoundRectCallout", "Speech Bubble: Rounded Rectangle"),
      item("wedgeEllipseCallout", "Speech Bubble: Oval"),
      item("cloudCallout", "Thought Bubble: Cloud"),
      item("borderCallout1", "Line Callout 1"),
      item("borderCallout2", "Line Callout 2"),
      item("borderCallout3", "Line Callout 3"),
      item("accentCallout1", "Line Callout 1 (Accent Bar)"),
      item("accentCallout2", "Line Callout 2 (Accent Bar)"),
      item("accentCallout3", "Line Callout 3 (Accent Bar)"),
      item("callout1", "Line Callout 1 (No Border)"),
      item("callout2", "Line Callout 2 (No Border)"),
      item("callout3", "Line Callout 3 (No Border)"),
      item("accentBorderCallout1", "Line Callout 1 (Border and Accent Bar)"),
      item("accentBorderCallout2", "Line Callout 2 (Border and Accent Bar)"),
      item("accentBorderCallout3", "Line Callout 3 (Border and Accent Bar)"),
    ],
  },
];

/** The gallery label for a preset, or the raw preset name off-gallery. */
export function shapeGalleryLabel(preset: string): string {
  for (const category of SHAPE_GALLERY) {
    const found = category.items.find((entry) => entry.preset === preset);
    if (found) return found.label;
  }
  return preset;
}
